Repository getmaxun/maxun, pull requests merged in 2024-11, with the labels that each got.

#104 chore: update concurrency.ts
  maxun-core/src/utils/concurrency.ts
Labels: Scope: Documentation

#125 chore: release public v0.0.1
  README.md
  docker-compose.yml
  index.html
  server/src/api/record.ts
  server/src/storage/mino.ts
  server/src/workflow-management/scheduler/index.ts
  src/apiConfig.js
  src/assets/maxunlogo.png
  src/components/molecules/ActionDescriptionBox.tsx
  src/components/molecules/NavBar.tsx
  src/components/organisms/RightSidePanel.tsx
Labels: Type: New Release

#146 feat: rename `API Docs` to `Website To API`
  src/components/organisms/MainMenu.tsx
Labels: Type: Enhancement

#153 feat: handle jwt token expiration
  package.json
  src/context/auth.tsx
Labels: Type: Bug, Type: Enhancement

#142 fix: google oauth redirect
  docker-compose.yml
  server/src/routes/auth.ts
  server/src/storage/mino.ts
  src/components/organisms/BrowserContent.tsx
Labels: Type: Bug, Status: In Review

#149 feat: generate encryption key if not provided or invalid
  server/src/utils/auth.ts
Labels: Type: Enhancement

#156 fix: gracefully handle jwt token decoding
  server/src/models/Robot.ts
  server/src/workflow-management/integrations/gsheet.ts
  src/context/auth.tsx
Labels: Type: Bug

#163 feat: export to csv
  esbuild.config.js
  src/components/molecules/RunContent.tsx
Labels: Type: Feature

#166 fix: download as csv button style
  src/components/molecules/RunContent.tsx
Labels: Type: Enhancement

#165 feat: show notification after successful google authentication
  package.json
  server/src/routes/auth.ts
  src/components/molecules/IntegrationSettings.tsx
Labels: Type: Enhancement

#172 chore: env sample values
  ENVEXAMPLE
  README.md
Labels: Scope: Documentation, Scope: Local Setup

#170 fix: remote browser rendering
  server/src/browser-management/classes/RemoteBrowser.ts
Labels: Type: Enhancement

#177 chore: minio success message
  server/src/storage/mino.ts
Labels: Type: Enhancement

#176 feat: show notification on robot delete with existing runs
  server/src/api/record.ts
  server/src/routes/storage.ts
  src/api/storage.ts
  src/components/molecules/RecordingsTable.tsx
  src/components/organisms/ApiKey.tsx
  src/components/organisms/BrowserWindow.tsx
Labels: Type: Enhancement, Status: In Review

#178 feat: register and login forms redesign
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: Type: Enhancement, Status: In Review

#191 feat: display robot limit in robot settings
  src/components/molecules/RobotSettings.tsx
Labels: Type: Enhancement

#187 feat: better nested elements capture in capture list
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
  src/components/molecules/RunContent.tsx
Labels: Type: Enhancement, Type: Feature

#173 feat: publish docker image
  .dockerignore
  docker-compose.yml
  server/Dockerfile
Labels: Type: Feature, Scope: Local Setup

#199 feat: add notification timeout
  src/components/molecules/RobotDuplicate.tsx
  src/components/molecules/RobotEdit.tsx
Labels: Type: Enhancement

#147 chore: release v0.0.2
  .dockerignore
  ENVEXAMPLE
  README.md
  docker-compose.yml
  esbuild.config.js
  package.json
  server/Dockerfile
  server/src/api/record.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/browser-management/inputHandlers.ts
  server/src/middlewares/auth.ts
  server/src/routes/auth.ts
  server/src/routes/proxy.ts
  server/src/routes/record.ts
  server/src/routes/storage.ts
  server/src/storage/mino.ts
  server/src/utils/auth.ts
  server/src/worker.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/scheduler/index.ts
  server/src/workflow-management/selector.ts
  src/api/storage.ts
  src/components/molecules/IntegrationSettings.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/RecordingsTable.tsx
  src/components/molecules/RobotDuplicate.tsx
  src/components/molecules/RobotEdit.tsx
  src/components/molecules/RobotSettings.tsx
  src/components/molecules/RunContent.tsx
  src/components/molecules/RunsTable.tsx
  src/components/organisms/ApiKey.tsx
  src/components/organisms/BrowserContent.tsx
  src/components/organisms/BrowserWindow.tsx
  src/components/organisms/MainMenu.tsx
  src/components/organisms/ProxyForm.tsx
  src/components/organisms/Recordings.tsx
  src/context/auth.tsx
  src/index.css
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: Type: New Release

#203 fix: min edit robot limit set to be 1
  src/components/molecules/RobotEdit.tsx
Labels: Type: Enhancement

#213 feat: improve logging
  server/src/api/record.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/routes/storage.ts
  server/src/workflow-management/scheduler/index.ts
Labels: Type: Enhancement

#212 feat: better notifications
  src/components/molecules/InterpretationButtons.tsx
  src/components/molecules/RecordingsTable.tsx
  src/components/molecules/SaveRecording.tsx
  src/components/organisms/ApiKey.tsx
  src/pages/MainPage.tsx
  src/pages/Register.tsx
Labels: Type: Enhancement, Scope: UI/UX

#215 feat: center progress
  src/components/organisms/ApiKey.tsx
Labels: Type: Enhancement, Scope: UI/UX
