Repository getmaxun/maxun, pull requests merged in 2024-12, with the labels that each got.

#217 feat: rearrange robot options
  src/components/molecules/RecordingsTable.tsx
Labels: Type: Enhancement, Scope: UI/UX

#219 feat: enhance output preview load
  src/components/molecules/InterpretationButtons.tsx
Labels: Type: Enhancement, Scope: UI/UX

#223 feat: dynamic public url
  ENVEXAMPLE
  README.md
  docker-compose.yml
  server/src/constants/config.ts
  server/src/routes/auth.ts
  server/src/server.ts
  vite.config.js
Labels: Type: Feature, Scope: Setup | Installation

#222 chore: add `.github` files
  .github/.github/COMMIT_CONVENTION.md
  .github/CODE_OF_CONDUCT.md
  README.md
Labels: Scope: Documentation, Type: Chore

#208 feat: handle browser link navigation
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/classes/Interpreter.ts
  src/components/organisms/RightSidePanel.tsx
Labels: Type: Feature, Status: In Review

#224 fix: emit socket `urlChanged` on frame navigation
  server/src/browser-management/classes/RemoteBrowser.ts
Labels: Type: Bug

#209 chore: release v0.0.3
  .github/.github/COMMIT_CONVENTION.md
  .github/CODE_OF_CONDUCT.md
  ENVEXAMPLE
  README.md
  docker-compose.yml
  esbuild.config.js
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  server/src/api/record.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/constants/config.ts
  server/src/routes/auth.ts
  server/src/routes/storage.ts
  server/src/server.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/classes/Interpreter.ts
  server/src/workflow-management/scheduler/index.ts
  src/components/molecules/InterpretationButtons.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/RecordingsTable.tsx
  src/components/molecules/RobotEdit.tsx
  src/components/molecules/SaveRecording.tsx
  src/components/organisms/ApiKey.tsx
  src/components/organisms/RightSidePanel.tsx
  src/pages/MainPage.tsx
  src/pages/Register.tsx
  vite.config.js
Labels: Type: New Release

#233 feat: product updates
  src/components/molecules/IntegrationSettings.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/Pair.tsx
  src/components/molecules/RobotDuplicate.tsx
Labels: Type: Enhancement, Type: Feature

#235 feat: rect dom depth information
  maxun-core/src/interpret.ts
  package.json
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement

#238 feat: apply conditional visual containment
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement

#244 feat: emit `setGetList` false socket event in pagination mode
  src/context/browserActions.tsx
Labels: Type: Enhancement

#246 feat: conditional selection
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement

#247 feat: support arm64 for docker backend
  Dockerfile
  server/Dockerfile
Labels: Type: Bug, Scope: Setup | Installation, Type: Chore

#248 fix: explicitly set easylist url
  maxun-core/src/interpret.ts
  server/src/browser-management/classes/RemoteBrowser.ts
Labels: Type: Bug

#225 chore: release v0.0.4
  Dockerfile
  docker-compose.yml
  maxun-core/package.json
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  package.json
  server/Dockerfile
  server/src/api/record.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/routes/storage.ts
  server/src/swagger/config.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/classes/Interpreter.ts
  server/src/workflow-management/scheduler/index.ts
  server/src/workflow-management/selector.ts
  src/components/molecules/IntegrationSettings.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/Pair.tsx
  src/components/molecules/RobotDuplicate.tsx
  src/context/browserActions.tsx
Labels: Type: New Release

#250 chore: use updated playwright image
  docker-compose.yml
  server/Dockerfile
Labels: Type: Enhancement

#251 chore: remove local note
  README.md
Labels: Scope: Documentation, Type: Chore

#256 feat: remove fe be mounts
  docker-compose.yml
Labels: Scope: Setup | Installation

#264 fix: scrapeList empty output preview
  server/src/workflow-management/classes/Generator.ts
Labels: Type: Bug

#259 feat: browser improvements
  maxun-core/src/interpret.ts
  server/src/browser-management/classes/RemoteBrowser.ts
Labels: Type: Enhancement, Status: Work In Progess

#266 feat: selection revamp
  maxun-core/src/browserSide/scraper.js
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement, Status: Work In Progess

#273 feat: selection for `<input>` tags
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement

#274 feat: clearer upgrade instructions
  src/components/molecules/NavBar.tsx
Labels: Type: Enhancement

#277 feat: auto logout
  src/context/auth.tsx
Labels: Type: Feature

#280 chore: format `concurreny.ts` in maxun-core
  maxun-core/src/utils/concurrency.ts
Labels: Scope: Documentation, Type: Chore

#279 chore: cleanup some code
  src/context/browserActions.tsx
Labels: Type: Chore

#278 feat(.github): delete duplicate directory
  .github/COMMIT_CONVENTION.md
Labels: Type: Chore

#242 feat: internationalization (i18n)
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  src/App.tsx
  src/components/molecules/ActionDescriptionBox.tsx
  src/components/molecules/BrowserRecordingSave.tsx
  src/components/molecules/ColapsibleRow.tsx
  src/components/molecules/IntegrationSettings.tsx
  src/components/molecules/InterpretationButtons.tsx
  src/components/molecules/InterpretationLog.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/RecordingsTable.tsx
  src/components/molecules/RobotDuplicate.tsx
  src/components/molecules/RobotEdit.tsx
  src/components/molecules/RobotSettings.tsx
  src/components/molecules/RunContent.tsx
  src/components/molecules/RunsTable.tsx
  src/components/molecules/SaveRecording.tsx
  src/components/molecules/ScheduleSettings.tsx
  src/components/organisms/ApiKey.tsx
  src/components/organisms/BrowserWindow.tsx
  src/components/organisms/MainMenu.tsx
  src/components/organisms/ProxyForm.tsx
  src/components/organisms/RightSidePanel.tsx
  src/i18n.ts
  src/index.tsx
  src/pages/Login.tsx
  src/pages/MainPage.tsx
  src/pages/RecordingPage.tsx
  src/pages/Register.tsx
Labels: Type: Feature, Status: In Review, Status: Work In Progess

#261 chore: release v0.0.5
  .github/COMMIT_CONVENTION.md
  Dockerfile
  README.md
  docker-compose.yml
  maxun-core/package.json
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  maxun-core/src/utils/concurrency.ts
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/Dockerfile
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/browser-management/inputHandlers.ts
  server/src/types/index.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
  src/App.tsx
  src/components/atoms/DatePicker.tsx
  src/components/atoms/DateTimeLocalPicker.tsx
  src/components/atoms/Dropdown.tsx
  src/components/atoms/TimePicker.tsx
  src/components/atoms/canvas.tsx
  src/components/molecules/ActionDescriptionBox.tsx
  src/components/molecules/BrowserRecordingSave.tsx
  src/components/molecules/ColapsibleRow.tsx
  src/components/molecules/IntegrationSettings.tsx
  src/components/molecules/InterpretationButtons.tsx
  src/components/molecules/InterpretationLog.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/RecordingsTable.tsx
  src/components/molecules/RobotDuplicate.tsx
  src/components/molecules/RobotEdit.tsx
  src/components/molecules/RobotSettings.tsx
  src/components/molecules/RunContent.tsx
  src/components/molecules/RunsTable.tsx
  src/components/molecules/SaveRecording.tsx
  src/components/molecules/ScheduleSettings.tsx
  src/components/organisms/ApiKey.tsx
  src/components/organisms/BrowserWindow.tsx
  src/components/organisms/MainMenu.tsx
  src/components/organisms/ProxyForm.tsx
  src/components/organisms/RightSidePanel.tsx
  src/context/auth.tsx
  src/context/browserActions.tsx
  src/context/globalInfo.tsx
  src/i18n.ts
  src/index.tsx
  src/pages/Login.tsx
  src/pages/MainPage.tsx
  src/pages/RecordingPage.tsx
  src/pages/Register.tsx
Labels: Type: New Release

#288 fix: preserve previous labels steps before adding list step
  src/context/browserSteps.tsx
Labels: Type: Bug

#289 chore: code cleanup
  server/src/routes/auth.ts
  server/src/workflow-management/scheduler/index.ts
  server/src/workflow-management/selector.ts
  src/components/molecules/RobotDuplicate.tsx
  src/components/organisms/RightSidePanel.tsx
  src/pages/Login.tsx
Labels: Type: Chore

#290 fix: i18n logs
  src/pages/Login.tsx
Labels: Type: Bug

#292 feat: enhance edit robot ui
  public/locales/en.json
  src/components/molecules/RobotEdit.tsx
Labels: Type: Enhancement

#293 chore: login translation switcher
  src/pages/Login.tsx
Labels: Type: Chore

#294 fix: move handleSave onClick to save button for edit robot
  src/components/molecules/RobotEdit.tsx
Labels: Type: Enhancement

#295 fix: avoid reload on duplicate robot cancel
  src/components/molecules/RobotDuplicate.tsx
Labels: Type: Enhancement

#297 chore: add refs in urls
  README.md
Labels: Type: Chore

#291 feat: better parsing of tables
  maxun-core/src/browserSide/scraper.js
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement, Status: Work In Progess

#299 feat: add delete functionality for text and list steps
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  src/components/organisms/RightSidePanel.tsx
Labels: Type: Feature
