Repository getmaxun/maxun, pull requests merged in 2025-06, with the labels that each got.

#628 feat: unified run creation and execution
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/browser-management/classes/BrowserPool.ts
  server/src/browser-management/controller.ts
  server/src/pgboss-worker.ts
  server/src/routes/record.ts
  server/src/routes/storage.ts
  server/src/server.ts
  src/api/recording.ts
  src/api/storage.ts
  src/components/robot/RecordingsTable.tsx
  src/pages/MainPage.tsx
Labels: Type: Feature, Scope: Infra

#630 chore: release v0.0.16
  .dockerignore
  Dockerfile.backend
  Dockerfile.frontend
  legacy/server/worker.ts
  maxun-core/package.json
  maxun-core/src/interpret.ts
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/browser-management/classes/BrowserPool.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/browser-management/controller.ts
  server/src/pgboss-worker.ts
  server/src/routes/record.ts
  server/src/routes/storage.ts
  server/src/schedule-worker.ts
  server/src/server.ts
  server/src/workflow-management/classes/Interpreter.ts
  src/api/recording.ts
  src/api/storage.ts
  src/components/browser/BrowserWindow.tsx
  src/components/recorder/Highlighter.tsx
  src/components/recorder/canvas.tsx
  src/components/robot/RecordingsTable.tsx
  src/components/run/ColapsibleRow.tsx
  src/components/run/RunContent.tsx
  src/components/run/Runs.tsx
  src/components/run/RunsTable.tsx
  src/pages/MainPage.tsx
Labels: Type: New Release

#646 chore: release v0.0.17
  README.md
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/browser-management/classes/bundle-rrweb.js
  server/src/browser-management/classes/rrweb-bundle.js
  server/src/browser-management/classes/rrweb-entry.js
  server/src/browser-management/controller.ts
  server/src/browser-management/inputHandlers.ts
  server/src/mcp-worker.ts
  server/src/server.ts
  server/src/workflow-management/classes/Generator.ts
  server/tsconfig.mcp.json
  src/components/browser/BrowserWindow.tsx
  src/components/dashboard/MainMenu.tsx
  src/components/dashboard/NavBar.tsx
  src/components/pickers/DatePicker.tsx
  src/components/pickers/DateTimeLocalPicker.tsx
  src/components/pickers/Dropdown.tsx
  src/components/recorder/DOMBrowserRenderer.tsx
  src/components/recorder/RightSidePanel.tsx
  src/helpers/clientListExtractor.ts
  src/helpers/clientSelectorGenerator.ts
Labels: Type: Next Release

#665 refactor: standardize ui file casing
  src/components/action/action-settings/Scrape.tsx
  src/components/action/action-settings/ScrapeSchema.tsx
  src/components/action/action-settings/Screenshot.tsx
  src/components/action/action-settings/Scroll.tsx
  src/components/action/action-settings/index.ts
  src/components/browser/BrowserNavBar.tsx
  src/components/browser/BrowserWindow.tsx
  src/components/browser/UrlForm.tsx
  src/components/pickers/DatePicker.tsx
  src/components/pickers/DateTimeLocalPicker.tsx
  src/components/pickers/Dropdown.tsx
  src/components/pickers/TimePicker.tsx
  src/components/recorder/Canvas.tsx
  src/components/ui/Form.tsx
  src/components/ui/buttons/Buttons.tsx
Labels: Type: Chore, Type: Refactor

#659 feat: faster screenshot output preview data
  server/src/browser-management/classes/RemoteBrowser.ts
  src/components/recorder/DOMBrowserRenderer.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/recorder/SidePanelHeader.tsx
  src/components/run/InterpretationButtons.tsx
  src/components/run/InterpretationLog.tsx
  src/context/browserSteps.tsx
Labels: Type: Bug, Type: Enhancement, Scope: Recorder

#661 fix: app crashing on decision handling
  server/src/workflow-management/classes/Generator.ts
Labels: Type: Bug
