Repository getmaxun/maxun, pull requests merged in 2025-04, with the labels that each got.

#515 chore: cleanup
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/middlewares/api.ts
  server/src/models/Robot.ts
  server/src/models/User.ts
  server/src/pgboss-worker.ts
  server/src/routes/auth.ts
  server/src/routes/record.ts
  server/src/routes/storage.ts
  server/src/schedule-worker.ts
  server/src/server.ts
  server/src/socket-connection/connection.ts
  server/src/storage/db.ts
  server/src/workflow-management/classes/Generator.ts
  src/components/browser/BrowserNavBar.tsx
  src/components/dashboard/MainMenu.tsx
  src/components/run/InterpretationLog.tsx
  src/components/run/Runs.tsx
  src/components/run/RunsTable.tsx
  src/components/ui/ConfirmationBox.tsx
  src/pages/MainPage.tsx
  src/pages/PageWrapper.tsx
  src/pages/RecordingPage.tsx
Labels: Type: Chore

#517 fix: remove page timeout for pagination
  maxun-core/src/interpret.ts
Labels: Type: Bug, Scope: Ext

#520 fix: change checkbox ui color
  src/components/action/ActionDescriptionBox.tsx
Labels: Scope: UI/UX

#510 ⚠️ feat: deprecate redis dependency from v0.0.13 ⚠️
  README.md
  docker-compose.yml
  package.json
Labels: Scope: Setup | Installation, Type: Infra, Type: ❗❗ .env Changes❗❗

#522 fix: output preview displays result immediately for scroll pagination
  maxun-core/src/interpret.ts
Labels: Type: Bug, Type: Enhancement

#518 chore(docker): !copy `maxun-core` during build
  Dockerfile
  server/Dockerfile
Labels: Type: Chore, Type: Infra

#523 fix: browser crashes due to scroll input event
  server/src/browser-management/inputHandlers.ts
Labels: Type: Bug

#525 fix: display the latest run name for each robot run
  src/components/run/RunsTable.tsx
Labels: Type: Bug, Scope: UI/UX

#527 fix: display abort status for aborted run
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  src/components/run/ColapsibleRow.tsx
Labels: Type: Bug, Scope: UI/UX

#530 feat: retrain robot
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/workflow-management/classes/Generator.ts
  src/components/browser/BrowserRecordingSave.tsx
  src/components/recorder/SaveRecording.tsx
  src/components/robot/RecordingsTable.tsx
  src/context/globalInfo.tsx
  src/pages/RecordingPage.tsx
Labels: Type: Feature

#532 fix: notifies run finished prematurely
  server/src/routes/record.ts
Labels: Type: Bug

#540 fix: Rendered browser image stretches for some sites
  server/src/browser-management/classes/RemoteBrowser.ts
Labels: Type: Bug

#542 feat: enable URL-safe encoding for DB passwords with special characters
  server/src/pgboss-worker.ts
  server/src/schedule-worker.ts
  server/src/storage/db.ts
Labels: Type: Enhancement, Scope: Setup | Installation, Type: Infra

#528 feat: execute abort operation using queue
  server/src/browser-management/controller.ts
  server/src/pgboss-worker.ts
  server/src/routes/storage.ts
  src/pages/MainPage.tsx
Labels: Type: Enhancement

#550 chore: pre-release v0.0.13
  maxun-core/package.json
  package.json
Labels: Type: New Release

#557 chore: add bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Type: Support

#565 feat: add meta content
  index.html
Labels: Type: Enhancement

#570 fix: destroy browser fallback
  server/src/routes/record.ts
Labels: Type: Bug

#569 feat: add wait until timeout state for navigation
  server/src/browser-management/inputHandlers.ts
  server/src/pgboss-worker.ts
Labels: Type: Bug

#560 feat: nginx config for self hosting
  nginx.conf
Labels: Type: Infra, Scope: Self Host

#558 fix: add page closed condition for highlighter
  server/src/browser-management/inputHandlers.ts
Labels: Type: Bug, Priority: High

#556 fix: capture text highlighting on discard
  src/components/recorder/RightSidePanel.tsx
  src/context/browserActions.tsx
Labels: Type: Bug, Scope: UI/UX

#562 feat: allow training multiple capture actions in one recording session
  maxun-core/src/interpret.ts
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/api/record.ts
  server/src/pgboss-worker.ts
  server/src/workflow-management/classes/Interpreter.ts
  server/src/workflow-management/integrations/airtable.ts
  server/src/workflow-management/integrations/gsheet.ts
  server/src/workflow-management/scheduler/index.ts
  src/components/browser/BrowserContent.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/run/InterpretationLog.tsx
  src/components/run/RunContent.tsx
  src/context/browserActions.tsx
Labels: Type: Feature
