Repository getmaxun/maxun, pull requests merged in 2025-02, with the labels that each got.

#427 feat: prevent hard reload on robot edit and duplication
  src/components/robot/RecordingsTable.tsx
  src/components/robot/RobotDuplicate.tsx
  src/components/robot/RobotEdit.tsx
  src/components/robot/RobotSettings.tsx
  src/context/globalInfo.tsx
Labels: Type: Enhancement, Scope: UI/UX

#429 feat: center menus
  src/components/dashboard/NavBar.tsx
Labels: Type: Enhancement, Scope: UI/UX

#396 feat: better selection
  server/src/workflow-management/selector.ts
  src/components/browser/BrowserWindow.tsx
Labels: Type: Enhancement, Status: On Hold

#428 fix: show better error message on user login
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/routes/auth.ts
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: Type: Bug, Scope: UI/UX

#403 feat: improve scraping stability
  maxun-core/src/interpret.ts
  server/src/workflow-management/classes/Generator.ts
Labels: Type: Enhancement

#399 chore: release v0.0.9
  maxun-core/package.json
  maxun-core/src/interpret.ts
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/routes/auth.ts
  server/src/routes/proxy.ts
  server/src/routes/storage.ts
  server/src/server.ts
  server/src/worker.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
  src/App.tsx
  src/api/storage.ts
  src/components/browser/BrowserWindow.tsx
  src/components/dashboard/NavBar.tsx
  src/components/robot/RecordingsTable.tsx
  src/components/robot/RobotDuplicate.tsx
  src/components/robot/RobotEdit.tsx
  src/components/robot/RobotSettings.tsx
  src/components/run/ColapsibleRow.tsx
  src/components/run/RunContent.tsx
  src/components/run/RunSettings.tsx
  src/components/run/RunsTable.tsx
  src/context/globalInfo.tsx
  src/context/theme-provider.tsx
  src/pages/Login.tsx
  src/pages/MainPage.tsx
  src/pages/Register.tsx
Labels: Type: New Release

#432 feat: consistent styling
  src/components/dashboard/NavBar.tsx
Labels: Type: Enhancement

#437 feat: toggle api key visibility
  src/components/api/ApiKey.tsx
Labels: Type: Enhancement

#441 fix: login title translation
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
Labels: Type: Enhancement

#443 feat: register translations
  public/locales/en.json
Labels: Type: Enhancement

#439 feat: better error messages
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/routes/auth.ts
  src/components/api/ApiKey.tsx
Labels: Type: Enhancement

#440 feat: check limit while processing workflow
  server/src/routes/storage.ts
Labels: Type: Enhancement

#435 fix: handle displayed input texts
  server/src/routes/storage.ts
  server/src/workflow-management/classes/Generator.ts
  src/components/robot/RobotEdit.tsx
Labels: Type: Bug

#445 fix: add error handling for selector generation
  server/src/workflow-management/selector.ts
Labels: Type: Bug

#446 fix: Return data even if single element exists
  maxun-core/src/interpret.ts
Labels: Type: Bug

#447 feat: navigate `/`
  src/components/dashboard/NavBar.tsx
Labels: Type: Enhancement

#438 chore: release v0.0.10
  maxun-core/package.json
  maxun-core/src/interpret.ts
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/routes/auth.ts
  server/src/routes/storage.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
  src/components/api/ApiKey.tsx
  src/components/dashboard/NavBar.tsx
  src/components/robot/RobotEdit.tsx
Labels: Type: New Release

#451 fix: Robot settings does not display
  server/src/routes/storage.ts
Labels: Type: Bug

#420 feat: airtable integration
  .gitignore
  ENVEXAMPLE
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/config/config.json
  server/migrations/20250125120216-add-airtable-columns-to-robot.js
  server/migrations/20250125182726-update-airtable-token-length.js
  server/migrations/20250207133740-added_table_id.js
  server/src/models/Robot.ts
  server/src/routes/auth.ts
  server/src/routes/storage.ts
  server/src/server.ts
  server/src/workflow-management/integrations/airtable.ts
  src/components/integration/IntegrationSettings.tsx
  src/components/robot/Recordings.tsx
Labels: Type: Feature

#455 feat: airtable integration (follow up)
  .gitignore
  ENVEXAMPLE
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  public/svg/airtable.svg
  public/svg/gsheet.svg
  server/config/config.json
  server/migrations/20250125120216-add-airtable-columns-to-robot.js
  server/migrations/20250125182726-update-airtable-token-length.js
  server/migrations/20250207133740-added_table_id.js
  server/src/models/Robot.ts
  server/src/routes/auth.ts
  server/src/routes/storage.ts
  server/src/server.ts
  server/src/workflow-management/integrations/airtable.ts
  src/components/integration/IntegrationSettings.tsx
  src/components/robot/Recordings.tsx
Labels: Type: Feature

#456 chore: -rm migrations
  .gitignore
  server/migrations/20250125120216-add-airtable-columns-to-robot.js
  server/migrations/20250125182726-update-airtable-token-length.js
  server/migrations/20250207133740-added_table_id.js
Labels: Type: Chore

#454 fix: display proxy config immediately after submission w/o hard refresh
  src/components/proxy/ProxyForm.tsx
Labels: Type: Bug

#458 fix: spacing between alert title and link
  src/components/integration/IntegrationSettings.tsx
Labels: Type: Enhancement
