Repository getmaxun/maxun, pull requests merged in 2025-01, with the labels that each got.

#307 fix: avoid ui shift on api key reveal
  src/components/organisms/ApiKey.tsx
Labels: Type: Enhancement

#308 feat: notify on schedule delete
  src/components/molecules/ScheduleSettings.tsx
Labels: Type: Enhancement

#316 fix: translation changes
  src/components/molecules/ActionDescriptionBox.tsx
  src/components/molecules/SaveRecording.tsx
Labels: Type: Enhancement

#315 fix: update custom limit if value >= 1
  src/components/organisms/RightSidePanel.tsx
Labels: Type: Enhancement

#296 feat: shadow dom selection
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  server/src/types/index.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
  server/src/workflow-management/utils.ts
  src/components/organisms/BrowserWindow.tsx
  src/context/browserSteps.tsx
Labels: Type: Feature, Status: In Review

#275 feat: support `iframe` extraction
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  server/src/types/index.ts
  server/src/workflow-management/selector.ts
  server/src/workflow-management/utils.ts
  src/components/organisms/BrowserWindow.tsx
Labels: Type: Feature, Status: Work In Progess

#313 feat: recorder performance improvements
  package.json
  perf/performance.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  src/components/atoms/canvas.tsx
  src/components/organisms/BrowserWindow.tsx
Labels: Type: Enhancement

#322 feat: handle selection for input & select tags
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement

#321 chore: release v0.0.6
  README.md
  docker-compose.yml
  maxun-core/package.json
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  package.json
  perf/performance.ts
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/routes/auth.ts
  server/src/types/index.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/scheduler/index.ts
  server/src/workflow-management/selector.ts
  server/src/workflow-management/utils.ts
  src/api/storage.ts
  src/api/workflow.ts
  src/components/atoms/canvas.tsx
  src/components/molecules/ActionDescriptionBox.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/RecordingsTable.tsx
  src/components/molecules/RobotDuplicate.tsx
  src/components/molecules/RobotEdit.tsx
  src/components/molecules/SaveRecording.tsx
  src/components/molecules/ScheduleSettings.tsx
  src/components/organisms/ApiKey.tsx
  src/components/organisms/BrowserWindow.tsx
  src/components/organisms/RightSidePanel.tsx
  src/context/browserSteps.tsx
  src/pages/Login.tsx
Labels: Type: New Release

#325 feat: latest compose changes for upgrade
  src/components/molecules/NavBar.tsx
Labels: Type: Enhancement

#326 feat: avoid virtual scroll in proxy info ui
  src/components/organisms/ProxyForm.tsx
Labels: Type: Enhancement, Scope: UI/UX

#328 chore: add docs to readme
  README.md
Labels: Scope: Documentation

#329 feat: toggle mode tooltip
  src/components/molecules/NavBar.tsx
Labels: Type: Enhancement, Scope: UI/UX

#330 feat: link docs to user menu
  src/components/molecules/NavBar.tsx
Labels: Scope: UI/UX

#337 feat: set output as default tab for run
  src/components/run/RunContent.tsx
Labels: Type: Enhancement

#334 feat: limit output preview data to 5
  server/src/workflow-management/classes/Interpreter.ts
Labels: Type: Enhancement

#300 feat: add message to display list being empty
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  src/components/recorder/RightSidePanel.tsx
Labels: Type: Enhancement

#314 feat: reset remote browser recording state
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  src/components/browser/BrowserRecordingSave.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/robot/RecordingsTable.tsx
  src/context/browserActions.tsx
  src/context/globalInfo.tsx
Labels: Type: Feature

#331 feat: much more reliable pagination
  maxun-core/src/interpret.ts
  server/src/workflow-management/classes/Generator.ts
  src/components/browser/BrowserWindow.tsx
  src/context/browserActions.tsx
Labels: Type: Feature

#343 feat: link docs to restart menu
  src/components/browser/BrowserRecordingSave.tsx
Labels: Type: Enhancement

#344 feat: recorder save panel UI consistency
  src/components/browser/BrowserRecordingSave.tsx
  src/components/recorder/SaveRecording.tsx
Labels: Type: Enhancement

#345 chore: remove selector console logs
  src/components/browser/BrowserWindow.tsx
Labels: Type: Chore

#346 chore: pre-release 0.0.7
  docker-compose.yml
  maxun-core/package.json
  package.json
Labels: Type: Chore

#350 chore: dead code elimination
  src/components/integration/IntegrationSettings.tsx
  src/components/recorder/AddWhatCondModal.tsx
  src/components/recorder/Highlighter.tsx
  src/components/recorder/LeftSidePanel.tsx
  src/components/recorder/LeftSidePanelContent.tsx
  src/components/recorder/PairDetail.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/recorder/canvas.tsx
  src/components/robot/Recordings.tsx
  src/components/robot/RobotDuplicate.tsx
  src/components/run/InterpretationButtons.tsx
Labels: Type: Chore

#351 fix: broken coordinates import in date picker
  src/components/pickers/DatePicker.tsx
Labels: Type: Bug

#354 feat: handle invalid routes
  src/components/dashboard/NotFound.tsx
  src/pages/PageWrappper.tsx
Labels: Scope: UI/UX

#355 fix: page wrapper
  src/App.tsx
  src/pages/PageWrapper.tsx
Labels: Type: Bug

#358 feat(ui): runs & robots loader
  src/components/robot/RecordingsTable.tsx
  src/components/run/RunsTable.tsx
Labels: Scope: UI/UX

#360 feat: use new icons for toggle mode
  src/components/dashboard/NavBar.tsx
Labels: Type: Enhancement

#362 chore: docker cleanup
  server/Dockerfile
Labels: Type: Chore

#364 feat: capitalize schedule
  src/components/robot/ScheduleSettings.tsx
Labels: Type: Enhancement

#365 fix: remove url creation and click race condition
  maxun-core/src/interpret.ts
Labels: Type: Bug

#363 feat: ability to update credentials for robots with authentication
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/models/Robot.ts
  server/src/routes/storage.ts
  server/src/workflow-management/classes/Generator.ts
  src/api/storage.ts
  src/components/recorder/SaveRecording.tsx
  src/components/robot/RecordingsTable.tsx
  src/components/robot/RobotEdit.tsx
  src/context/globalInfo.tsx
Labels: Type: Feature

#375 feat: change credentials based on input type
  maxun-core/src/interpret.ts
  server/src/routes/storage.ts
  server/src/workflow-management/classes/Generator.ts
  src/api/storage.ts
  src/components/robot/RobotEdit.tsx
Labels: Type: Enhancement

#378 fix: add position of text for input click event
  server/src/workflow-management/classes/Generator.ts
Labels: Type: Bug

#367 feat: db sync in dev mode
  server/src/storage/db.ts
Labels: Type: Infra

#368 feat: authentication prompt before robot creation
  public/locales/en.json
  src/components/robot/RecordingsTable.tsx
Labels: Type: Feature

#386 fix: prevent page reload on run trigger to open remote browser
  server/src/browser-management/classes/BrowserPool.ts
  server/src/browser-management/controller.ts
  server/src/routes/record.ts
  server/src/workflow-management/classes/Interpreter.ts
  src/pages/MainPage.tsx
Labels: Type: Bug

#387 fix: Empty label on recording shows error
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
Labels: Type: Bug

#390 fix: open modal to fetch spreadsheets after google oauth
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/routes/auth.ts
  src/components/integration/IntegrationSettings.tsx
  src/components/robot/Recordings.tsx
Labels: Type: Bug, Type: Enhancement

#391 feat: execute run as a separate job
  server/src/routes/storage.ts
  server/src/worker.ts
  src/pages/MainPage.tsx
Labels: Type: Feature

#385 feat: edit robot inputs
  src/components/robot/RecordingsTable.tsx
  src/components/robot/RobotEdit.tsx
Labels: Type: Feature

#392 chore: pre-release 0.0.8
  maxun-core/package.json
  package.json
Labels: Type: New Release

#395 feat: use `libgbm1` instead of `libgbm-dev`
  server/Dockerfile
Labels: Type: Infra

#357 chore: release v0.0.8
  README.md
  maxun-core/package.json
  maxun-core/src/interpret.ts
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/Dockerfile
  server/src/routes/auth.ts
  server/src/routes/storage.ts
  server/src/storage/db.ts
  server/src/workflow-management/classes/Generator.ts
  src/App.test.tsx
  src/App.tsx
  src/api/storage.ts
  src/components/dashboard/NavBar.tsx
  src/components/dashboard/NotFound.tsx
  src/components/integration/IntegrationSettings.tsx
  src/components/pickers/DatePicker.tsx
  src/components/recorder/AddWhatCondModal.tsx
  src/components/recorder/Highlighter.tsx
  src/components/recorder/LeftSidePanel.tsx
  src/components/recorder/LeftSidePanelContent.tsx
  src/components/recorder/PairDetail.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/recorder/SaveRecording.tsx
  src/components/recorder/canvas.tsx
  src/components/robot/Recordings.tsx
  src/components/robot/RecordingsTable.tsx
  src/components/robot/RobotDuplicate.tsx
  src/components/robot/RobotEdit.tsx
  src/components/robot/ScheduleSettings.tsx
  src/components/run/InterpretationButtons.tsx
  src/components/run/RunsTable.tsx
  src/context/globalInfo.tsx
  src/pages/PageWrapper.tsx
Labels: Type: New Release

#382 feat: optimize robots and runs table ui
  src/components/robot/RecordingsTable.tsx
  src/components/run/RunsTable.tsx
Labels: Type: Enhancement

#398 feat: display loader on robot run
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  src/components/run/RunContent.tsx
Labels: Type: Enhancement, Scope: UI/UX

#401 fix: Run status displays failed on system termination
  server/src/server.ts
  server/src/worker.ts
Labels: Type: Bug, Scope: UI/UX

#402 feat: display proper message for run exists notification
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
Labels: Type: Enhancement, Scope: UI/UX

#405 chore(ui): cleanup old theme
  src/App.tsx
Labels: Type: Refactor

#412 feat(cloud): authenticated requests extend
  server/src/routes/auth.ts
  server/src/routes/proxy.ts
Labels: Type: Enhancement

#411 feat: remove project name from upgrade button
  src/components/dashboard/NavBar.tsx
Labels: Type: Enhancement

#406 feat: handle `color=error` in all modes
  src/context/theme-provider.tsx
Labels: Type: Enhancement, Scope: UI/UX

#415 feat: separate pagination for runs and nested runs
  src/components/run/RunsTable.tsx
Labels: Type: Bug, Type: Enhancement, Scope: UI/UX

#419 feat: sort robots and runs table
  src/components/robot/RecordingsTable.tsx
  src/components/run/RunsTable.tsx
Labels: Type: Enhancement, Scope: UI/UX

#421 feat: remove star counter
  src/components/dashboard/NavBar.tsx
Labels: Type: Enhancement

#417 feat: display currently running robot run
  server/src/routes/storage.ts
  src/api/storage.ts
  src/components/run/ColapsibleRow.tsx
  src/components/run/RunsTable.tsx
  src/pages/MainPage.tsx
Labels: Type: Enhancement, Scope: UI/UX

#422 feat: user menu revamp
  src/components/dashboard/NavBar.tsx
Labels: Type: Enhancement

#423 fix: alignment of nav items
  src/components/dashboard/NavBar.tsx
Labels: Type: Enhancement

#425 feat: prevent flickering of table ui on empty data
  src/components/robot/RecordingsTable.tsx
  src/components/run/RunsTable.tsx
Labels: Type: Bug, Scope: UI/UX
