Repository getmaxun/maxun, pull requests merged in 2025-07, with the labels that each got.

#673 feat: add mcp integration option
  public/svg/mcp.svg
  src/components/integration/IntegrationSettings.tsx
Labels: Type: Enhancement

#672 feat: inject snapshot bundle in browser context
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/browser-management/inputHandlers.ts
  src/components/recorder/DOMBrowserRenderer.tsx
Labels: Type: Enhancement, Scope: Recorder

#675 feat: better, faster, smarter capture list
  maxun-core/src/browserSide/scraper.js
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/workflow-management/classes/Generator.ts
  src/components/browser/BrowserWindow.tsx
  src/components/recorder/DOMBrowserRenderer.tsx
  src/components/recorder/RightSidePanel.tsx
  src/context/globalInfo.tsx
  src/helpers/clientListExtractor.ts
  src/helpers/clientSelectorGenerator.ts
Labels: Type: Enhancement

#674 feat: enhance snapshot rendering
  src/components/integration/IntegrationSettings.tsx
  src/components/recorder/DOMBrowserRenderer.tsx
Labels: Type: Enhancement, Scope: UI/UX, Scope: Recorder

#682 fix: href selector revamp
  src/helpers/clientSelectorGenerator.ts
Labels: Type: Bug

#686 fix: main menu tab spacing
  src/components/dashboard/MainMenu.tsx
Labels: Type: Bug, Scope: UI/UX

#685 feat: validate credentials
  server/src/routes/auth.ts
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: Type: Enhancement, Scope: UI/UX

#680 feat: display capture text data in vertical (column-wise) format
  server/src/workflow-management/integrations/airtable.ts
  server/src/workflow-management/integrations/gsheet.ts
  src/components/run/InterpretationLog.tsx
  src/components/run/RunContent.tsx
Labels: Type: Enhancement, Scope: UI/UX

#683 feat: do not show recording url before browser is available
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
Labels: Type: Enhancement

#694 feat(maxun-core): child extraction + deep shadow dom
  maxun-core/src/browserSide/scraper.js
  src/components/browser/BrowserWindow.tsx
  src/components/recorder/DOMBrowserRenderer.tsx
  src/components/recorder/RightSidePanel.tsx
  src/context/browserSteps.tsx
  src/helpers/clientListExtractor.ts
  src/helpers/clientSelectorGenerator.ts
Labels: Type: Enhancement, Scope: Ext

#699 Add Turkish Language Support
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/tr.json
  public/locales/zh.json
Labels: Scope: i18n Translations

#703 feat: enhance ui for oss upgrade
  src/components/dashboard/NavBar.tsx
Labels: Scope: UI/UX

#708 fix: attribute selection window closes
  src/components/browser/BrowserWindow.tsx
  src/components/ui/GenericModal.tsx
Labels: Scope: Recorder

#709 feat: improved overall selector generation
  src/helpers/clientSelectorGenerator.ts
Labels: Type: Enhancement, Scope: Recorder
