Repository getmaxun/maxun, pull requests merged in 2025-08, with the labels that each got.

#723 fix: tabular data highlighting
  src/helpers/clientSelectorGenerator.ts
Labels: Type: Bug, Scope: Recorder

#724 feat: increase job execution duration
  server/src/pgboss-worker.ts
Labels: Type: Enhancement

#727 feat: sync lang translations
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/tr.json
  public/locales/zh.json
Labels: Scope: i18n Translations

#728 feat: focused element typing
  server/src/browser-management/inputHandlers.ts
  src/components/recorder/DOMBrowserRenderer.tsx
Labels: Type: Bug, Type: Enhancement

#736 feat: enable client-side notifications for all runs
  server/src/server.ts
  src/context/socket.tsx
  src/pages/MainPage.tsx
Labels: Scope: Infra

#719 feat: modal to UI pages
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/tr.json
  public/locales/zh.json
  src/components/robot/Recordings.tsx
  src/components/robot/pages/RobotConfigPage.tsx
  src/components/robot/pages/RobotDuplicatePage.tsx
  src/components/robot/pages/RobotEditPage.tsx
  src/components/robot/pages/RobotIntegrationPage.tsx
  src/components/robot/pages/RobotSettingsPage.tsx
  src/components/robot/pages/ScheduleSettingsPage.tsx
Labels: Type: Enhancement, Scope: UI/UX

#742 fix: recorder crashes
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
Labels: Type: Bug, Scope: Recorder

#749 fix: remove deprecated server side screenshot highlighting that destroyed execution context
  server/src/browser-management/inputHandlers.ts
Labels: Type: Bug, Scope: Recorder

#751 fix: highlighting gets stuck on heavy sites
  src/helpers/clientSelectorGenerator.ts
Labels: Type: Bug
