Repository getmaxun/maxun, pull requests merged in 2025-05, with the labels that each got.

#580 fix: add `maxun-core` in deps
  package.json
Labels: Scope: Dependencies

#563 feat: prune pg session interval
  server/src/server.ts
Labels: Type: Infra

#572 feat: order robots according to updatedAt
  server/src/routes/storage.ts
  src/components/robot/RecordingsTable.tsx
Labels: Type: Enhancement, Scope: UI/UX

#573 feat: re-render robot list on retrain
  src/components/robot/RecordingsTable.tsx
Labels: Type: Enhancement, Scope: UI/UX

#575 fix: date format for duplicate robots
  server/src/routes/storage.ts
  src/components/robot/RecordingsTable.tsx
Labels: Type: Bug, Scope: UI/UX

#577 fix: limit text overflows right side panel
  src/components/recorder/RightSidePanel.tsx
Labels: Type: Bug, Scope: UI/UX

#579 feat: support for editing multiple capture list limits
  server/src/routes/storage.ts
  src/api/storage.ts
  src/components/robot/RobotEdit.tsx
Labels: Type: Bug, Type: Enhancement

#582 feat: fetch multiple robot action results for api run
  server/src/api/record.ts
Labels: Type: Enhancement

#584 feat: ts compatible session store
  ENVEXAMPLE
  README.md
  server/src/server.ts
Labels: Type: Infra, Type: ❗❗ .env Changes❗❗

#583 feat: faster output preview
  maxun-core/src/interpret.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/workflow-management/classes/Interpreter.ts
  src/components/browser/BrowserWindow.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/run/InterpretationLog.tsx
  src/context/browserSteps.tsx
Labels: Type: Enhancement

#566 chore: release v0.0.14
  .github/ISSUE_TEMPLATE/bug_report.yml
  ENVEXAMPLE
  README.md
  index.html
  maxun-core/package.json
  maxun-core/src/interpret.ts
  nginx.conf
  package.json
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  server/src/api/record.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/browser-management/inputHandlers.ts
  server/src/pgboss-worker.ts
  server/src/routes/record.ts
  server/src/routes/storage.ts
  server/src/server.ts
  server/src/workflow-management/classes/Interpreter.ts
  server/src/workflow-management/integrations/airtable.ts
  server/src/workflow-management/integrations/gsheet.ts
  server/src/workflow-management/scheduler/index.ts
  src/api/storage.ts
  src/components/browser/BrowserContent.tsx
  src/components/browser/BrowserWindow.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/robot/RecordingsTable.tsx
  src/components/robot/RobotEdit.tsx
  src/components/run/InterpretationLog.tsx
  src/components/run/RunContent.tsx
  src/context/browserActions.tsx
  src/context/browserSteps.tsx
Labels: Type: New Release

#594 fix: remove `version` from docker compose
  docker-compose.yml
Labels: Scope: Setup | Installation

#595 feat: byop config
  public/locales/en.json
  src/components/proxy/ProxyForm.tsx
Labels: Type: Enhancement

#597 feat: update robot description for multiple actions
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
Labels: Type: Enhancement, Scope: UI/UX

#600 feat: override anchor container selection
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement, Scope: Ext
