Repository getmaxun/maxun, pull requests merged in 2025-03, with the labels that each got.

#459 feat: check for headers and append data to gsheet
  server/src/workflow-management/integrations/gsheet.ts
Labels: Type: Bug, Type: Enhancement

#464 fix: remove blue auto highlight in text fields
  src/index.css
Labels: Type: Bug, Scope: UI/UX

#463 feat: airtable environment variables
  README.md
Labels: Type: ❗❗ .env Changes❗❗

#462 feat: improve highlighting and data extraction
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement

#467 feat: support multiple browser instances
  server/src/api/record.ts
  server/src/browser-management/classes/BrowserPool.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/browser-management/controller.ts
  server/src/browser-management/inputHandlers.ts
  server/src/routes/record.ts
  server/src/routes/storage.ts
  server/src/routes/workflow.ts
  server/src/socket-connection/connection.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/scheduler/index.ts
  src/components/browser/BrowserWindow.tsx
Labels: Type: Feature

#468 fix: use runByUserId
  server/src/routes/storage.ts
Labels: Type: Bug

#472 feat: support redis auth
  ENVEXAMPLE
  README.md
  server/src/worker.ts
Labels: Type: Feature, Type: Infra, Type: ❗❗ .env Changes❗❗

#475 fix: resolve handle url change
  src/components/browser/BrowserNavBar.tsx
Labels: Type: Bug

#477 feat: browser perf log cleanup
  src/components/recorder/canvas.tsx
Labels: Type: Bug

#453 chore: release v0.0.11
  .gitignore
  ENVEXAMPLE
  README.md
  maxun-core/package.json
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  package.json
  perf/performance.ts
  public/locales/de.json
  public/locales/en.json
  public/locales/es.json
  public/locales/ja.json
  public/locales/zh.json
  public/svg/airtable.svg
  public/svg/gsheet.svg
  server/config/config.json
  server/src/api/record.ts
  server/src/browser-management/classes/BrowserPool.ts
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/browser-management/controller.ts
  server/src/browser-management/inputHandlers.ts
  server/src/models/Robot.ts
  server/src/pgboss-worker.ts
  server/src/routes/auth.ts
  server/src/routes/record.ts
  server/src/routes/storage.ts
  server/src/routes/workflow.ts
  server/src/server.ts
  server/src/socket-connection/connection.ts
  server/src/worker.ts
  server/src/workflow-management/classes/Generator.ts
  server/src/workflow-management/integrations/airtable.ts
  server/src/workflow-management/integrations/gsheet.ts
  server/src/workflow-management/scheduler/index.ts
  server/src/workflow-management/selector.ts
  src/components/api/ApiKey.tsx
  src/components/browser/BrowserNavBar.tsx
  src/components/browser/BrowserRecordingSave.tsx
  src/components/browser/BrowserWindow.tsx
  src/components/integration/IntegrationSettings.tsx
  src/components/proxy/ProxyForm.tsx
  src/components/recorder/Renderer.tsx
  src/components/recorder/SaveRecording.tsx
  src/components/recorder/canvas.tsx
  src/components/robot/Recordings.tsx
  src/components/robot/RecordingsTable.tsx
  src/components/run/ColapsibleRow.tsx
  src/components/run/RunContent.tsx
  src/index.css
  src/pages/MainPage.tsx
  src/pages/PageWrapper.tsx
  src/pages/RecordingPage.tsx
  src/routes/userRoute.tsx
Labels: Type: New Release

#483 fix: adjust margin for consistent spacing
  src/components/api/ApiKey.tsx
Labels: Type: Bug, Scope: UI/UX

#478 Feat: Resized Browser
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/pgboss-worker.ts
  src/components/browser/BrowserContent.tsx
  src/components/browser/BrowserTabs.tsx
  src/components/browser/BrowserWindow.tsx
  src/components/recorder/Highlighter.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/recorder/canvas.tsx
  src/components/run/InterpretationLog.tsx
  src/constants/const.ts
  src/context/browserDimensions.tsx
  src/helpers/coordinateMapper.ts
  src/helpers/dimensionUtils.ts
  src/index.css
Labels: Type: Enhancement

#482 feat: click next improvements
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
Labels: Type: Enhancement, Scope: Ext

#486 fix: attribute selection on link selections
  server/src/workflow-management/selector.ts
Labels: Type: Bug

#485 feat: edit robot target url
  server/src/routes/storage.ts
  src/api/storage.ts
  src/components/robot/RobotEdit.tsx
Labels: Type: Feature

#487 fix: excess gap between text fields
  src/components/robot/RobotEdit.tsx
Labels: Type: Bug, Scope: UI/UX

#484 fix: remote browser height sizing
  src/helpers/dimensionUtils.ts
Labels: Type: Enhancement

#488 feat: better DOM parsing and highlighting
  server/src/workflow-management/selector.ts
Labels: Type: Enhancement, Scope: Ext

#490 feat: reduce highlighter thickness
  src/components/recorder/Highlighter.tsx
Labels: Type: Enhancement, Scope: UI/UX

#491 feat: enhance screencast quality
  server/src/browser-management/classes/RemoteBrowser.ts
  src/helpers/dimensionUtils.ts
  src/index.css
Labels: Type: Enhancement

#493 fix: improve list container detection and highlighting
  server/src/workflow-management/selector.ts
Labels: Type: Bug, Scope: Ext

#495 feat: migrate session storage to postgres
  package.json
  server/src/server.ts
Labels: Type: Infra

#499 docs: redis port minor changes
  README.md
Labels: Scope: Documentation, Type: Enhancement

#496 feat: remote browser performance optimization
  server/src/browser-management/classes/RemoteBrowser.ts
  src/components/recorder/Highlighter.tsx
  src/helpers/coordinateMapper.ts
Labels: Type: Enhancement, Status: Work In Progess

#497 refactor: enhance RunsTable component layout
  src/components/run/RunsTable.tsx
Labels: Type: Enhancement, Scope: UI/UX

#500 feat: automate db migrations
  .sequelizerc
  docker-compose.yml
  package.json
  server/Dockerfile
  server/docker-entrypoint.sh
  server/src/db/config/database.js
  server/src/db/migrate.js
  server/src/db/models/index.js
Labels: Type: Chore, Type: Infra

#479 chore: release v0.0.12
  .sequelizerc
  README.md
  maxun-core/package.json
  maxun-core/src/browserSide/scraper.js
  maxun-core/src/interpret.ts
  package.json
  server/docker-entrypoint.sh
  server/src/browser-management/classes/RemoteBrowser.ts
  server/src/db/config/database.js
  server/src/db/migrate.js
  server/src/db/migrations/20250327111003-add-airtable-columns.js
  server/src/db/models/index.js
  server/src/pgboss-worker.ts
  server/src/routes/storage.ts
  server/src/server.ts
  server/src/workflow-management/selector.ts
  src/api/storage.ts
  src/components/api/ApiKey.tsx
  src/components/browser/BrowserContent.tsx
  src/components/browser/BrowserTabs.tsx
  src/components/browser/BrowserWindow.tsx
  src/components/recorder/Highlighter.tsx
  src/components/recorder/RightSidePanel.tsx
  src/components/recorder/canvas.tsx
  src/components/robot/RobotEdit.tsx
  src/components/run/InterpretationLog.tsx
  src/constants/const.ts
  src/context/browserDimensions.tsx
  src/helpers/coordinateMapper.ts
  src/helpers/dimensionUtils.ts
  src/index.css
Labels: Type: New Release

#508 fix: chromium installation for local setup
  README.md
Labels: Scope: Setup | Installation

#507 feat: use pgBoss for scheduling robots
  server/src/browser-management/controller.ts
  server/src/pgboss-worker.ts
  server/src/routes/storage.ts
  server/src/schedule-worker.ts
  server/src/server.ts
  server/src/socket-connection/connection.ts
  server/src/workflow-management/scheduler/index.ts
Labels: Type: Infra
